---
- hosts: all
  become: true

  tasks:
    - name: Print all the ansible gathered ansible_fatcs
      ansible.builtin.debug:
        var: ansible_facts

    - name: shutdown ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian"
       #ansible_facts['os_family'] == "RedHat"